name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        node-version:
        - 10.x
        - 12.x
        - 14.x
        - 16.x
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Use Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      env:
        PYTHON_VERSION: 3.8
    - name: Install MSBuild
      if: matrix.os == 'windows-latest'
      uses: microsoft/setup-msbuild@v1.0.2
    - run: npm i
    - run: prebuild --strip # npm run build --if-present
    - run: npm test
